### ISSUE TITLE
address all idnits

### ISSUE THREAD

**Issue by ekline** [google/self-published-geo#15]
See http://www.ietf.org/tools/idnits/ .

We should do this once all all other issues are closed and changes to the text are essentially done.

**Comment by ekline** [comment]
Hmmm...I'm not sure I actually understand how to read this idnits output.  :-/

**Comment by ekline** [comment]
Ah, this is much more readable (than uploading a txt file):

    https://www6.ietf.org/tools/idnits?url=https://www.ietf.org/archive/id/draft-google-self-published-geofeeds-04.txt

**Comment by ekline** [comment]
I think the latest version addresses all legitimate nits.  I'll have a look when the upload window re-opens.

**Comment by wkumari** [comment]
Newest version (-05) addresses all open issues.

**Comment by wkumari** [comment]
... and I forgot to close. Done.
