### ISSUE TITLE
extract python code and make sure unittests pass

### ISSUE THREAD

**Issue by ekline** [google/self-published-geo#16]
Additionally, consider:

  [1] python2 versus python3?

  [2] see if CI can be set up (though this code requires the IP address library)

**Comment by wkumari** [comment]
I believe that the preferred method is to wrap the code in the document with `<CODE BEGINS>` and `<CODE ENDS>` tags, and then use something like [https://github.com/mbj4668/rfcstrip/blob/master/rfcstrip](https://github.com/mbj4668/rfcstrip/blob/master/rfcstrip) to strip it out and test it.

**Comment by wkumari** [comment]
This is done. Closing.

**Comment by wkumari** [comment]
I lied -- this is not done, but we closed it anyway.
