### ISSUE TITLE
alpha2iso should allow non-conforming (EU) codes

### ISSUE THREAD

**Issue by geeohgeegeeoh** [google/self-published-geo#23]
Minor nit, can you modify the paragraph about the semantic intent and conformance for alpha2iso to permit use of EU?  It's in the reserved/exceptional set, arguably this is "ok" as-is and you can close the file.  https://www.iso.org/obp/ui/#iso:code:3166:EU puts it "off to one side" of the official countryCode list.

A nit-picker might disagree. But equally, not. I'm fine if you choose to close this with a sigh.

**Comment by ekline** [comment]
https://github.com/google/self-published-geo/pull/25

PTAL
